version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo: 
          ContainerName: "infra-stg-atlantis-terragrunt"
          ContainerPort: 80
