Resources:
  - infra-dev-atlantis-terragrunt:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition: <TASK_DEFINITION>
      LoadBalancerInfo: 
          ContainerName: "atlantis-terragrunt" 
          ContainerPort: 80
